rvm:
  - 2.4.4
  - 2.5.1
  - 2.6.3
gemfile:
  - gemfiles/Gemfile-activemodel-4.2.x
  - gemfiles/Gemfile-activemodel-5.0.x
  - gemfiles/Gemfile-activemodel-5.1.x
  - gemfiles/Gemfile-activemodel-5.2.x
  - gemfiles/Gemfile-activemodel-6.0.x
  - gemfiles/Gemfile-activemodel-6.1.x
matrix:
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile-activemodel-4.2.x
sudo: false
