name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        rails: ['6.1', '7.0', '7.1']

    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies for gemfiles/Gemfile-activemodel-${{ matrix.rails }}
        run: bundle install --gemfile=gemfiles/Gemfile-activemodel-${{ matrix.rails }}

      - name: Run tests
        run: bundle exec rspec
