name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.7']
        gemfile:
          - gemfiles/Gemfile-activemodel-5.0.x
          - gemfiles/Gemfile-activemodel-5.1.x
          - gemfiles/Gemfile-activemodel-5.2.x
          - gemfiles/Gemfile-activemodel-6.0.x
          - gemfiles/Gemfile-activemodel-6.1.x
          - gemfiles/Gemfile-activemodel-7.0.x

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies for ${{ matrix.gemfile}}
        run: bundle install --gemfile=${{ matrix.gemfile  }}
      - name: Run tests
        run: bundle exec rspec
