name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
        gemfile:
          - gemfiles/Gemfile-activemodel-7.1.x
          - gemfiles/Gemfile-activemodel-7.2.x
          - gemfiles/Gemfile-activemodel-8.0.x

    name: Ruby ${{ matrix.ruby }} / Gemfile {{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies for ${{ matrix.gemfile }}
        run: bundle install --gemfile=${{ matrix.gemfile }}

      - name: Run tests
        run: bundle exec rspec
